- lib/graphql/batch/execution_strategy.rb
- test/batch_test.rb
- test/support/schema.rb
There was a bug in https://github.com/Shopify/graphql-batch/pull/3 with waiting for promises in the result of a selection for a list.  E.g. a selection for products would resolve to a list of promises for the variants if any batch loads were needed for variant fields.
After assigning the result of a promise for a selection to a field, I recursively called the code to turn a value into a promise to return from the `.then` block so that the outer `Promise.all` would wait for that promise.
Previously the wrapping of values with promises was handled in the selection resolution for each object.  However, since we need to handle sub-promises, we can move the promise wrapping so that it is done once (recursively) for the whole operation.  I think this also simplifies the code …
> fix: Wait for subpromises after a list promise is resolved.

- README.md
- lib/graphql/batch.rb
- lib/graphql/batch/execution_strategy.rb
- lib/graphql/batch/executor.rb
- lib/graphql/batch/loader.rb
- test/batch_test.rb
- test/loader_test.rb
- test/support/db.rb
- test/support/loaders.rb
- test/support/schema.rb
I noticed a problem with the RecordLoader example in the README when records were missing.  We weren't fulfilling the load for ids if they are missing in the query result.
When we do come across a bug in a loader, we should also make these errors easier to debug by checking for unfulfilled promises in the loader and in the executor to provide a helpful error message.
I also noticed that we aren't actually handling a GraphQL::ExecutionError properly, since it wasn't behaving as if the error was raised in a field's resolve proc.  The error was causing the whole request to fail, without showing other fields, instead of being treated as a field error.
* I added `GraphQL::Batch::Loader#fulfilled?` to make it easier to check for unfulfilled promises in `#perform`
* …
> Improve error handling

- lib/graphql/batch/execution_strategy.rb
This simplification avoids interfering with the changes made in https://github.com/rmosolgo/graphql-ruby/pull/94, working in conjunction with my upstream pull request https://github.com/rmosolgo/graphql-ruby/pull/100 which allows this to keep working on the next version of graphql-ruby.
> Pass execution error to super in get_finished_value override

- graphql-batch.gemspec
- lib/graphql/batch/version.rb
- test/batch_test.rb
In `lib/graphql/batch/version`, we're accidentally defining a top-level constant that's unused anywhere else in the ecosystem: `Graphql`. It looks like this probably happened during generating the gem, but was never updated to match the `GraphQL` constant that's used everywhere else in this gem and other gems.
> Fix errant `Graphql` constant

- lib/graphql/batch/executor.rb
- lib/graphql/batch/promise.rb
- test/batch_test.rb
- test/executor_test.rb
- test/support/db.rb
When depending on GraphQL::Batch for avoiding N+1 queries, it becomes important to test for unbatched queries.
I have managed to accomplish that by overriding GraphQL::Field to separate the resolver into a preload_proc and a resolve_proc, so the preload_proc can do the batch loading then we can assert no queries are performed in the resolve_proc.  However, this required the result of the preload_proc to be memoized so it could be used in the resolve_proc and also doesn't test the normal code path for executing a graphql query.
Add a GraphQL::Batch::Executor#loading attribute which is set to `true` when performing a batch load and `false` otherwise.
This could be used in an `ActiveSupport::Notifications.subscribe` block to detect queries that are performed while …
> Add support for checking for unbatched queries by checking a loading flag

- lib/graphql/batch/loader.rb
- test/loader_test.rb
Loaders that take the same grouping arguments to the `for` method can cause conflicts.  This becomes obvious when working with singleton loaders, loaders with no grouping arguments passed to `for`.  In these cases, loads from different loaders will get grouped together and performed using the loader instance for the first class used for batch loading.
Prepend the loader class to the grouping arguments to use for the loader key.
> Also group loaders by their class

- lib/graphql/batch/loader.rb
- test/loader_test.rb
Not all loaders require parameters, and using this is a bit awkward:
promise = SpecialLoader.for.load(1)
This is a bit nicer:
promise = SpecialLoader.load(1)
After this change, tests still passing:
```
Finished in 0.017371s, 1669.4325 runs/s, 2302.6655 assertions/s.
29 runs, 40 assertions, 0 failures, 0 errors, 0 skips
```
> Nicer syntax for parameterless executors

- README.md
- test/batch_test.rb
Noticed our tests were failing on the latest version of `graphql-ruby`. This fixes it.
Also added badges to the README.
There's a ton of warnings when we run the tests which we may want to fix, but that can be done outside this PR.
cc @dylanahsmith
> Fix tests on latest graphql

- README.md
This is very minor but I noticed it while reading through the project README.
> Add missing syntax highlight in README

- test/batch_test.rb
- test/support/schema.rb
re: rmosolgo/graphql-ruby#296 and closes #18 
This adds two regression tests for non-nullable fields that raise.
:eyes: @dylanahsmith
> Add regression test for execution errors in non-nullable fields

- lib/graphql/batch/loader.rb
- test/loader_test.rb
Fixes #21
@Mange what do you think about a runtime error of "Loader can't be used after batch load" to avoid confusion?
> Provide a useful error when load is called after perform

- lib/graphql/batch/execution_strategy.rb
- test/batch_test.rb
- test/support/loaders.rb
- test/support/schema.rb
@cjoudrey & @eapache please review
We were getting a `GraphQL::InvalidNullError: Cannot return null for non-nullable field` exception from a type check that was being done after preloading associations for a field in Shopify.  The type check was returning an GraphQL::ExecutionError, so the error should have been handled and serialized as part of the query result.
I was able to simplify the code to reproduce the bug down to this script
```ruby
require 'graphql/batch'
class EchoLoader < GraphQL::Batch::Loader
def perform(keys)
keys.each { |key| fulfill(key, key) }
end
end
QueryType = GraphQL::ObjectType.define do
name "Query"
field :test, !types.String do
resolve -> (obj, args, ctx) {
EchoLoader.load(nil).then do
raise GraphQL::ExecutionError, "test error"
end
}
end
end
Schema = …
```
> Fix handling ExecutionError in promise callback of non-null field

- lib/graphql/batch/loader.rb
- test/loader_test.rb
@cjoudrey & @xuorig please review
cc @Mange since you opened #21
This allows a loader to be re-used so that it can be used to cache previous loads.
Currently this will require keeping a reference to the loader to re-use it.  A follow-up will be needed to have the executor keep references to the old loaders during a GraphQL request.
> Allow loaders to be re-used so they can cache loads.

- lib/graphql/batch/execution_strategy.rb
- lib/graphql/batch/mutation_execution_strategy.rb
- test/batch_test.rb
- test/support/schema.rb
Closes #30
@rmosolgo I added a regression test for the broken code you tried to remove in #30 and fixed it without swapping the execution strategy
@xuorig & @cjoudrey looks like our batching has been broken for mutations subselections which this fixes
> Fix batching loading in mutation subselection

- lib/graphql/batch/loader.rb
- test/loader_test.rb
@cjoudrey, @xuorig
I tried to bump graphql-batch in Shopify to use the latest commit on master and got an exception that I reproduced with the added regression test.
```
GraphQL::Batch::LoaderTest#test_loader_for_without_load:
NoMethodError: undefined method `each' for nil:NilClass
/Users/dylansmith/src/graphql-batch/lib/graphql/batch/loader.rb:83:in `each_pending_promise'
/Users/dylansmith/src/graphql-batch/lib/graphql/batch/loader.rb:41:in `rescue in resolve'
/Users/dylansmith/src/graphql-batch/lib/graphql/batch/loader.rb:36:in `resolve'
/Users/dylansmith/src/graphql-batch/lib/graphql/batch/executor.rb:27:in `block in tick'
/Users/dylansmith/src/graphql-batch/lib/graphql/batch/executor.rb:57:in `with_loading'
/Users/dylansmith/src/graphql-batch/lib/graphql/batch/executor.rb:27:in `tick' …
```
> Fix resolving loader when Loader.for is used without load

- README.md
- graphql-batch.gemspec
- lib/graphql/batch.rb
- lib/graphql/batch/execution_strategy.rb
- lib/graphql/batch/executor.rb
- lib/graphql/batch/loader.rb
- test/loader_test.rb
@rmosolgo @xuorig
promise.rb 0.7.2 now supports `.sync` being called on the result of Promise.all, so we don't need to warn about that in the README.
Also, in the next version of graphql-ruby we can use `lazy_resolve(Promise, :sync)` in the Schema without the need to use GraphQL::Batch::Promise.all in resolve methods.
I have also tested this PR with the following changes to test with the graphql-ruby lazy resolution API
```diff
diff --git a/Gemfile b/Gemfile
index fa75df1..a7f313a 100644
--- a/Gemfile
+++ b/Gemfile
@@ -1,3 +1,5 @@
source 'https://rubygems.org'
gemspec
+
+gem 'graphql', github: 'rmosolgo/graphql-ruby', branch: 'master'
diff --git a/test/support/schema.rb b/test/support/schema.rb
index dfaa799..238b4ac 100644
--- a/test/support/schema.rb
+++ b/test/support/schema.rb
@@ …
```
> Take advantage of improvements in promise.rb

- lib/graphql/batch/execution_strategy.rb
- lib/graphql/batch/executor.rb
- lib/graphql/batch/loader.rb
- lib/graphql/batch/mutation_execution_strategy.rb
- lib/graphql/batch/promise.rb
- test/loader_test.rb
@rmosolgo, @xuorig & @cjoudrey 
As pointed out in https://github.com/Shopify/graphql-batch/pull/33#discussion_r88349952, when using graphql-batch outside of the execution strategy, we run the risk of leaky state.  This could be a problem when using the graphql gem's new lazy resolution API, but it could also be a problem in tests.
As such, I think we should move away from depending on global state, even if we support one for convenience and backwards compatibility.
The thread local executor is used for three purposes right now:
1. stores a list of loaders
2. executes those loaders
3. keeps track of the loading flag that unit tests can check to catch unbatched queries
promise.rb 0.7.2 now keeps track of the source of the promise and uses that to sync the promise by default.  All that is …
> Allow loaders to be used without an executor

- .gitignore
- .travis.yml
- Gemfile.graphql13
- lib/graphql/batch.rb
- lib/graphql/batch/setup.rb
- test/graphql_test.rb
- test/lazy_resolve_test.rb
@rmosolgo
cc @cjoudrey & @xuorig 
This should support both the new lazy resolution API that will come in graphql-ruby 1.3.0 as well as the old execution strategy, while also not breaking when the execution strategies are removed.
Nothing in this PR is specific to graphql-ruby 1.3.0 other than test/lazy_resolve_test.rb which uses feature detection to only run the test if the lazy_resolve method is defined, so we should be able to make a graphql-batch 0.3.0 release without waiting for graphql-ruby 1.3.0
> Support graphql-ruby lazy resolution API

- lib/graphql/batch/loader.rb
- test/loader_test.rb
Forgetting to use `GraphQL::Batch.batch`, or to use the Setup instrumenter when using graphql-ruby results in a `NoMethodError: undefined method `loaders' for nil:NilClass`.
Would be pretty useful to display a good error message there, wdyt ?
> No executor error

- README.md
- lib/graphql/batch.rb
- lib/graphql/batch/execution_strategy.rb
- test/support/schema.rb
Adds the `use` method so `GraphQL::Batch` can be used as a plugin in `define` blocks.
This replaces https://github.com/Shopify/graphql-batch/pull/49
/cc @cjoudrey
> Make GraphQL::Batch a plugin by adding `use`

- test/execution_strategy_test.rb
- test/graphql_test.rb
I noticed in https://github.com/Shopify/graphql-batch/pull/52 that our tests are now failing with graphql 1.6.0, since it made some breaking changes.
It looks like setting the execution strategy now longer works upstream unless `GraphQL::Query::Executor` is used directly, which is deprecated.
Change the tests for this legacy feature to use `GraphQL::Query::Executor` instead of using GraphQL::Schema#execute.  I used a subclass to ignore the warnings for that test.
> Fix tests for execution strategies

- lib/graphql/batch/loader.rb
- test/graphql_test.rb
Stop deleting loaders from the cache.
This improves loader reuse.
> Improve loader reuse

- lib/graphql/batch/loader.rb
- test/graphql_test.rb
- test/support/loaders.rb
- test/support/schema.rb
cc @staugaard
The loader re-use added by https://github.com/Shopify/graphql-batch/pull/53 also re-used the loaders and their resolved promises after a mutation field is resolved.
[GraphQL::GraphQLTest#test_mutation_execution](https://github.com/Shopify/graphql-batch/blob/v0.3.3/test/graphql_test.rb#L297) was a test that was supposed to catch this bug, but it was using `CounterLoader.for(ctx).load` where load was defined in CounterLoader with `def load(key=Object.new)`, so it was actually using a unique key for each load which prevented it from ever re-using the result of a previous load.
I've reverted https://github.com/Shopify/graphql-batch/pull/53 to fix the bug and updated the test to use override `cache_key` to use the `object_id` of the array that is used to hold the counter.
If the …
> Prevent loader re-use after mutations

- lib/graphql/batch.rb
- lib/graphql/batch/setup_multiplex.rb
- test/multiplex_test.rb
This patch adds support for a shared batching context when multiple queries are run concurrently. Is it something you're interested in for this gem?
Single queries are still supported because graphql 1.6+ treats `Schema#execute` as a special case of `Schema#multiplex`: a multiplex with one query. So it's still covered by `instrument(:multiplex,...)`.
> feat(GraphQL::Batch::SetupMultiplex) use multiplex instrumentation to share a batching context

- README.md
- examples/association_loader.rb
- examples/record_loader.rb
Fixes #24
This adds a couple of examples for a RecordLoader and AssociationLoader that work with Active Record and links to those examples in the README.
Each of these handle a problem that a naive loader would have:
* RecordLoader type casts keys to avoid to fulfilling the wrong key when the wrong type is provided
* AssociationLoader preloads the association on all records, even if some share the same id
These are just examples, since I didn't want to add an active record dependency to this library.
> Add Active Record AssociationLoader and RecordLoader examples

- lib/graphql/batch.rb
- lib/graphql/batch/loader.rb
- lib/graphql/batch/mutation_execution_strategy.rb
- lib/graphql/batch/setup.rb
- lib/graphql/batch/setup_multiplex.rb
- test/graphql_test.rb
- test/support/schema.rb
Fixes #43
https://github.com/Shopify/graphql-batch/pull/56 reverted a change that re-uses loaders after they are loaded so that they aren't re-used after a mutation.
Add field instrumentation to wrap the resolve proc for mutation fields in order to clear the loaders cache before and after it is called.
Identifying which fields were mutation fields required having the schema in the instrumentation, so I changed the setup modules into classes that take the schema as an initializer.  Before #51 we recommended using `instrument(:query, GraphQL::Batch::Setup)` in the README, so I have added class methods to deprecate that old usage.
> Re-use loaders after they have been performed, but clear on mutation

- .travis.yml
- lib/graphql/batch.rb
- lib/graphql/batch/execution_strategy.rb
- lib/graphql/batch/executor.rb
- lib/graphql/batch/loader.rb
- lib/graphql/batch/mutation_execution_strategy.rb
- lib/graphql/batch/promise.rb
- lib/graphql/batch/setup.rb
Fixes #60 (cc @jpserra)
@arthurschreiber would this remove the need for https://github.com/lgierth/promise.rb/pull/35 ?
As I mentioned in #60 
> The reason for the difference is more of an implementation detail. The only difference between ::Promise and GraphQL::Batch::Promise is that GraphQL::Batch::Promise overrides defer so that we can use GraphQL::Batch::Executor.current.loading in tests to detect when an unbatched query is performed in a test.
so I refactored the code so that GraphQL::Batch::Loader's fulfill and reject methods call `executor.around_promise_callbacks do` around the actually fulfillment or rejection of the promise, allowing the executor to set its loading flag to `false` before promise callbacks are called and reset back to `true` for the remainder of the loaders …
> Return a normal Promise object from GraphQL::Batch::Loader#load

- lib/graphql/batch.rb
- lib/graphql/batch/setup.rb
- lib/graphql/batch/setup_multiplex.rb
- test/custom_executor_test.rb
* Changed: GraphQL::Batch.use can take optional `custom_executor`
* `GraphQL::Batch::Setup` and `GraphQL::Batch::SetupMultiplex` updated to hold reference to the executor class (defaults to GraphQL::Batch::Executor) as instance variables.
@dylanahsmith @eapache @swalkinshaw 👋 ~~I'm looking to verify my approach here before continuing. See the linked Shopify/shopify PR for more context.~~ Updated according PR review comments so far.
> Allow custom executors

- lib/graphql/batch/loader.rb
- test/loader_test.rb
A test within Shopify that sets an expectation on Loader#perform to raise an error exposed a problem with our implementation of `Loader#reject_pending_promises`:
```
NameError: undefined local variable or method `load_keys' for #
graphql-batch/lib/graphql/batch/loader.rb:120:in `reject_pending_promises'
```
The method was not previously covered in tests, and the NameError it raises obscures other exceptions raised within `perform`. This PR fixes this.
> Fix reject_pending_promises handling

- lib/graphql/batch.rb
- lib/graphql/batch/executor.rb
- lib/graphql/batch/setup.rb
- test/batch_test.rb
This PR removes `GraphQL::Batch:: NestedError` and the associated restriction on nested queries. See https://github.com/Shopify/graphql-batch/issues/70 for details.
> Allow nested queries.

- lib/graphql/batch.rb
- lib/graphql/batch/executor.rb
- lib/graphql/batch/loader.rb
- test/executor_test.rb
- test/loader_test.rb
When ending a batch with no executor, we would try to raise a `NoExecutorError` in `Executor` but a name error would occur because that class is defined in `Loader`.
In this PR I'm moving this error to `GraphQL::Batch` instead since it may happen both in `Loader` and `Executor`.
Also added a test to ensure this code path is tested.
> Fix NoExecutorError

- README.md
`load_many` method is implemented via https://github.com/Shopify/graphql-batch/commit/1c92c89f98c0abec7c9cb1a145c04b82f5e38f9d but never documented, I think it is a really useful feature and should be documented.
Feel free to change wording, it might not be the best description.
> Document load_many method

- lib/graphql/batch/loader.rb
This fixes an issue where `Loader#check_for_broken_promises` was generating a large amount of unused `Promise::BrokenError` objects and strings in case there were no broken promises after the loader finished execution.
By skipping the error object creation for promises that are no longer pending, we can also skip generating these objects.
> Do not try to reject pending promises.

- test/custom_executor_test.rb
- test/graphql_test.rb
- test/support/schema.rb
This rewrites the test schema from the old API to the new class-based API introduced in graphql 1.8 for better forwards compatibility.
The only test updates needed were camelizing some underscored field names.
> Update test schema to use class-based API

- test/graphql_test.rb
GraphQL::ExecutionStrategyTest used to override schema_execute to share the GraphQL::GraphQLTest tests before https://github.com/Shopify/graphql-batch/pull/94 removed the old execution strategies.  So now we can call execute on the schema directly.
> test: Remove no longer needed schema_execute helper method

- .travis.yml
- Gemfile
- README.md
- lib/graphql/batch.rb
- lib/graphql/batch/mutation_field_extension.rb
- test/support/schema.rb
~~This doesn't quite work yet, and I think it's because of the changes in https://github.com/rmosolgo/graphql-ruby/pull/1984. (Previously, there were cases when execution would proceed eagerly _down_ the tree, but in that PR, it was changed to _always_ resolve each level of depth before proceeding to further depths.)~~ 
~~I think this means that the interpreter has to _hardcode_ handling for mutation root fields, which isn't too surprising. I'll take a look.~~ Fixed by https://github.com/rmosolgo/graphql-ruby/pull/2097
This adds a CI build for 1.9.0.pre4 and and implementation that uses a FieldExtension. I think it will work pretty well, the only problem will be if people do: 
```ruby
use GraphQL::Batch
mutation(Types::Mutation)
```
It will still work _for now_ because plugins are applied …
> Try using a field extension for 1.9 interpreter

- README.md
- lib/graphql/batch.rb
- test/support/schema.rb
I think this fixes #101, @Mange can you confirm that?
cc @rmosolgo 
We assumed that we could always use field extensions with version 1.9 of the graphql gem but that doesn't work if the fields are defined on a mutation root object type that doesn't use the new class-based API.
Make the use of field extensions conditional upon having a `schema.mutation.metadata[:type_class]`.  I also changed the test schema to use a non-class based mutation root when not testing with the interpreter.
I also noticed that the README documentation was saying that `use GraphQL::Batch` needed to follow `use GraphQL::Execution::Interpreter`, but it is actually the `mutation` line that it needs to follow.
> Fix compatibility with non-class based mutation root object

- README.md
Using `id` from keyword argument in resolver instead of undefined `args[:id]`.
> Fix typo in README.md for Resolver Arguments

- Gemfile
- lib/graphql/batch.rb
graphql 1.10.0 will change the structure of class-based schemas so that they _don't_ delegate to `.define`-style singletons anymore. Naturally, this breaks stuff 😅 . 
I've added a 1.10.0.pre2 build to CI (which should cover all the structural changes) and updated the code to pass.
Fixes #115
> Update plugin for 1.10-dev

- graphql-batch.gemspec
Github had an alert on a vulnerability in the development dependency rake (https://github.com/advisories/GHSA-jppv-gw3r-w3q8).
Use the recommended constraint `spec.add_development_dependency "rake", ">= 12.3.3"` since we don't have any incompatibilities with newer versions of rake.
> Bump the rake dev dependency

- .travis.yml
- lib/graphql/batch/loader.rb
Fixes #126
GraphQL::Batch::Loader was using `*group_args` for forwarding arguments which won't forward keyword arguments in the future which may be used by the loader (e.g. we do that in the RecordLoader example).
Use `*group_args` for argument forwarding for older ruby versions, since passing keyword arguments an initializer that doesn't take them causes problems for old versions of ruby.
As an optimization, I used `...` syntax for argument forwarding for MRI ruby 2.7+ which avoids some object allocation for the splat parameters.  I had to eval the ruby code using the new syntax to avoid causing parsing problems for older versions of ruby.
I also changed the CI config to test ruby 2.7.
> Fix ruby 2.7 keyword arguments warning

- examples/active_storage_loader.rb
- examples/window_key_loader.rb
I love when a project has a ton of examples that can be used and extended. Example: https://github.com/zeit/next.js/tree/canary/examples
I wanted to add 2 examples that solve somewhat challenging batch issues:
- Loading `has_many` relationships where you want the first N records. This can be accomplished using window functions in Postgres.
- Loading Active Storage attachments (can often produce 2N + 1 queries).
> Adding examples for Active Storage Loader and Postgres Window Loader

- .github/workflows/ci.yml
> Add Ruby 3.0 to CI

- examples/active_storage_loader.rb
- examples/association_loader.rb
- examples/http_loader.rb
- examples/record_loader.rb
- examples/window_key_loader.rb
When using the loader of examples, the following error occurred.
```
wrong number of arguments (given 2, expected 0)
/app/app/loader/association_loader.rb:10:in `initialize'
```
The problem is passing arguments to the `super`, so I fixed it so that no arguments are passed.
> Fix errors in examples

- examples/association_loader.rb
Currently running this example code with rails 7 yields the following warning:
```
DEPRECATION WARNING: `preload` is deprecated and will be removed in Rails 7.0. Call `Preloader.new(kwargs).call` instead.
```
Updating the preloader code to use kwargs and call silences the warning.
> Fix AssociationLoader Rails 7 Deprecation Warning

- README.md
It seems that this project doesn't use Travis now.
> Fix a link to CI

- lib/graphql/batch/loader.rb
For optimal performance in Ruby 3.2, it is preferable to define instance variables in a consistent order.
Based on production data, it seems that Batch::Loader is one of the main offenders in our app:
```
Shape Edges Report
-----------------------------------
169  @cache
130  @queue
127  @executor
125  @sql_counter
119  @loader_key
```
> Improve Shapes Friendliness of Batch::Loader

- .github/workflows/ci.yml
- graphql-batch.gemspec
These changes adds support for Ruby 3.2 by bumping the minimum required version of `graphql` from `1.10.0` to `1.12.18` which fixes a Ruby 3.2 incompatibility related to the use of include in refinements as fixed in this PR:
https://github.com/rmosolgo/graphql-ruby/pull/3674
> Add support for Ruby 3.2

- lib/graphql/batch/loader.rb
- lib/graphql/batch/version.rb
TL;DR This PR adds a wrapper method around the `#perform` method. This allows us to wrap the `#perform` method within code blocks that would help with measuring the performance in terms of time taken or the number of sql queries executed or anything else
Today, we have to override the `#resolve` method as demonstrated by the example below.
```ruby
class BaseLoader < GraphQL::Batch::Loader
def resolve
return if resolved?
load_keys = queue
@queue = nil
instrument_sql_requests do
perform(load_keys)
end
check_for_broken_promises(load_keys)
rescue => err
reject_pending_promises(load_keys, err)
end
def instrument_sql_requests
SQLCounter.run { yield }
end
end
```
With the proposed changes, the `#resolve` method does not need to be overridden and a system can call multiple wrappers if required. …
> Add a custom wrapper around #perform

- README.md
- lib/graphql/batch/loader.rb
- test/loader_test.rb
Sometimes data is loaded through some means, which will also later be loaded by an independent batch data loader. It can be convenient to then prime the cache of that data data loader with the already loaded data, to remove redundant calls.
The use-case I have can be summarized by this query:
```
query {
shopsFollowed(first: 10) {
nodes {
id
followedByMe
}
}
}
```
The `shopsFollowed` resolver performs a query to load 10 shops that the current user follows. This is returned as the `Shop` type, which is used extensively in the API. The `Shop.followedByMe` field returns a boolean of whether the current user follows the shop. It's backed by a custom batch data loader.
For the specific `shopsFollowed` use-case, we know that all the shops returned are followed by the current user, so there's no …
> Priming the cache
